<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "teasermenu"
 *
 * Auto generated by Extension Builder 2017-03-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Teaser Menu',
    'description' => 'Flexible Fluid teaser menu navigation',
    'category' => 'plugin',
    'author' => 'Josef Glatz',
    'author_email' => 'josef.glatz@typo3.org',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
